### ISSUE TITLE
Vendor shoud be unknown as it is unsupported

### ISSUE THREAD

**Issue by kakarotto67** [BIZMONT/KottansTask#3]
Pass "36148900647913" to GetCreditCardVendor method
Expected result: unknown (as we do not support Diners vendor, but the number is of that vendor, check [this](http://support.worldpay.com/support/kb/bg/testandgolive/tgl5103.html) )
Actual result: Maestro

**Comment by BIZMONT** [comment]
Could not see the same issue with these card number.
