### ISSUE TITLE
Vendor should be Unknown but it isn't

### ISSUE THREAD

**Issue by kakarotto67** [BIZMONT/KottansTask#4]
Pass "50000000000006114" into GetCreditCardVendor method
Expected result: Unknown (as it has 17 digits)
Actual result: Maestro

**Comment by BIZMONT** [comment]
For Maestro cards, this should not be an issue. Because Maestro has card number length from 12 to 19 digits. [Wiki](https://en.wikipedia.org/wiki/Bank_card_number)

**Comment by kakarotto67** [comment]
Yeah, number matches your regex and length, but it isn't valid at all. Pass it to your IsCreditCardNumberValid method and you will see it.
